version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    volumes:
      - ./models:/app/models  # Persist model data
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is sent straight to terminal
    restart: unless-stopped

networks:
  app:
    driver: bridge