version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./backend/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app
    container_name: movie-recommendation
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app:
    driver: bridge