version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app
    container_name: backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app:
    driver: bridge

volumes:
  backend-models: