channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair
    - pandas
    - streamlit
    - scikit-surprise
    - pip:
        - pickle
        - scikit-surprise
        - requests